/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package psproject_v5.form;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import psproject_v5.threads.ServerThread;

/**
 *
 * @author aleks
 */
public class FrmServer extends javax.swing.JFrame {

    private ServerThread serverThread;

    /**
     * Creates new form FrmServer
     */
    public FrmServer() {
        initComponents();
        menuServerItemStop.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuServer = new javax.swing.JMenu();
        menuServerItemStart = new javax.swing.JMenuItem();
        menuServerItemStop = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        menuConfigItemView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuServer.setText("Server");

        menuServerItemStart.setText("Start");
        menuServerItemStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServerItemStartActionPerformed(evt);
            }
        });
        menuServer.add(menuServerItemStart);

        menuServerItemStop.setText("Stop");
        menuServerItemStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServerItemStopActionPerformed(evt);
            }
        });
        menuServer.add(menuServerItemStop);

        jMenuBar1.add(menuServer);

        menuConfig.setText("Config");

        menuConfigItemView.setText("View");
        menuConfigItemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigItemViewActionPerformed(evt);
            }
        });
        menuConfig.add(menuConfigItemView);

        jMenuBar1.add(menuConfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuConfigItemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigItemViewActionPerformed
        JDialog frmConfig = new FrmConfig(this, true);
        frmConfig.setVisible(true);
    }//GEN-LAST:event_menuConfigItemViewActionPerformed

    private void menuServerItemStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServerItemStartActionPerformed
        try {
            // TODO add your handling code here:
            serverThread = new ServerThread();
            serverThread.start();
            menuServerItemStop.setEnabled(true);
            menuConfigItemView.setEnabled(false);
            menuServerItemStart.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(FrmServer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuServerItemStartActionPerformed

    private void menuServerItemStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServerItemStopActionPerformed
        // TODO add your handling code here:
        serverThread.stopServer();
        menuServerItemStop.setEnabled(false);
        menuConfigItemView.setEnabled(true);
        menuServerItemStart.setEnabled(true);
    }//GEN-LAST:event_menuServerItemStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenuItem menuConfigItemView;
    private javax.swing.JMenu menuServer;
    private javax.swing.JMenuItem menuServerItemStart;
    private javax.swing.JMenuItem menuServerItemStop;
    // End of variables declaration//GEN-END:variables
}
